//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wolffun.CodeGen.Addressables
{
    
    
    public sealed class AddressableKey
    {
        
        public sealed class TexturesAvartar
        {
            
            public const string _00_2_Component = "00_2_Component";
            
            public const string _00_3_FunctionIcons = "00_3_FunctionIcons";
            
            public const string _00_4_EquipmentIcons = "00_4_EquipmentIcons";
            
            public const string _00_4_Icons1 = "00_4_Icons1";
            
            public const string _00_4_Icons2 = "00_4_Icons2";
            
            public const string _00_5_Guild_Flag = "00_5_Guild_Flag";
            
            public const string _00_6_Chest = "00_6_Chest";
            
            public const string _01_Login = "01_Login";
            
            public const string _02_Title = "02_Title";
            
            public const string _03_TitleStart = "03_TitleStart";
            
            public const string _04_NetworkError = "04_NetworkError";
            
            public const string _05_Home = "05_Home";
            
            public const string _06_PopupLogin = "06_PopupLogin";
            
            public const string _07_PopupSignup = "07_PopupSignup";
            
            public const string _08_PopupOffline = "08_PopupOffline";
            
            public const string _09_PopupName = "09_PopupName";
            
            public const string _10_ADRemove = "10_ADRemove";
            
            public const string _11_PopupChecking = "11_PopupChecking";
            
            public const string _12_PopupEUALPrivacy = "12_PopupEUALPrivacy";
            
            public const string _13_PopupUpdate = "13_PopupUpdate";
            
            public const string _14_PopupMessage = "14_PopupMessage";
            
            public const string _20_PlayType1 = "20_PlayType1";
            
            public const string _20_PlayType2 = "20_PlayType2";
            
            public const string _20_PlayType3 = "20_PlayType3";
            
            public const string _21_PlayBoss = "21_PlayBoss";
            
            public const string _22_PlayContinue = "22_PlayContinue";
            
            public const string _23_PlayPause = "23_PlayPause";
            
            public const string _24_PlayResult = "24_PlayResult";
            
            public const string _30_Tutorial = "30_Tutorial";
            
            public const string _31_CharacterSelect = "31_CharacterSelect";
            
            public const string _32_Heroes = "32_Heroes";
            
            public const string _33_Equipment = "33_Equipment";
            
            public const string _33_EquipmentDetail1 = "33_EquipmentDetail1";
            
            public const string _33_EquipmentDetail2 = "33_EquipmentDetail2";
            
            public const string _33_EquipmentDetail3 = "33_EquipmentDetail3";
            
            public const string _34_GuideBook = "34_GuideBook";
            
            public const string _40_Stage = "40_Stage";
            
            public const string _41_Setting = "41_Setting";
            
            public const string _42_Language = "42_Language";
            
            public const string _43_Shop_Chest = "43_Shop_Chest";
            
            public const string _44_Shop_Gold = "44_Shop_Gold";
            
            public const string _45_Shop_Gem = "45_Shop_Gem";
            
            public const string _46_BattlePass = "46_BattlePass";
            
            public const string _47_Missions = "47_Missions";
            
            public const string _48_Guild = "48_Guild";
            
            public const string _50_Ranking = "50_Ranking";
            
            public const string _60_PowerSave = "60_PowerSave";
            
            public const string _61_LoadingBar = "61_LoadingBar";
            
            public const string _62_LevelUp = "62_LevelUp";
            
            public const string _63_Rate = "63_Rate";
            
            public const string _64_RewardDaily = "64_RewardDaily";
            
            public const string _65_RewardWeek = "65_RewardWeek";
            
            public const string _66_Roulette = "66_Roulette";
        }
    }
}
