//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wolffun.CodeGen.Addressables {
    
    
    public sealed class AddressableKey {
        
        public sealed class BuiltInData {
            
            public const string Resources = "Resources";
            
            public const string EditorSceneList = "EditorSceneList";
        }
        
        public sealed class DefaultLocalGroup {
        }
        
        public sealed class PrefabsDragons {
            
            public const string Dragon11 = "Dragon_11";
            
            public const string Dragon11Attack = "Dragon_11@Attack";
            
            public const string Dragon11AttackStand = "Dragon_11@AttackStand";
            
            public const string Dragon11Breath = "Dragon_11@Breath";
            
            public const string Dragon11Damage = "Dragon_11@Damage";
            
            public const string Dragon11Die = "Dragon_11@Die";
            
            public const string Dragon11Idle = "Dragon_11@Idle";
            
            public const string Dragon11Run = "Dragon_11@Run";
            
            public const string Dragon11Stand = "Dragon_11@Stand";
            
            public const string Dragon11Walk = "Dragon_11@Walk";
            
            public const string Dragon12 = "Dragon_12";
            
            public const string Dragon12Attack = "Dragon_12@Attack";
            
            public const string Dragon12AttackStand = "Dragon_12@AttackStand";
            
            public const string Dragon12Breath = "Dragon_12@Breath";
            
            public const string Dragon12Damage = "Dragon_12@Damage";
            
            public const string Dragon12Die = "Dragon_12@Die";
            
            public const string Dragon12Idle = "Dragon_12@Idle";
            
            public const string Dragon12Run = "Dragon_12@Run";
            
            public const string Dragon12Stand = "Dragon_12@Stand";
            
            public const string Dragon12Walk = "Dragon_12@Walk";
            
            public const string Dragon13 = "Dragon_13";
            
            public const string Dragon13Attack = "Dragon_13@Attack";
            
            public const string Dragon13AttackStand = "Dragon_13@AttackStand";
            
            public const string Dragon13Breath = "Dragon_13@Breath";
            
            public const string Dragon13Damage = "Dragon_13@Damage";
            
            public const string Dragon13Die = "Dragon_13@Die";
            
            public const string Dragon13Idle = "Dragon_13@Idle";
            
            public const string Dragon13Run = "Dragon_13@Run";
            
            public const string Dragon13Stand = "Dragon_13@Stand";
            
            public const string Dragon13Walk = "Dragon_13@Walk";
            
            public const string Dragon21 = "Dragon_21";
            
            public const string Dragon21Attack = "Dragon_21@Attack";
            
            public const string Dragon21AttackStand = "Dragon_21@AttackStand";
            
            public const string Dragon21Breath = "Dragon_21@Breath";
            
            public const string Dragon21Damage = "Dragon_21@Damage";
            
            public const string Dragon21Die = "Dragon_21@Die";
            
            public const string Dragon21Idle = "Dragon_21@Idle";
            
            public const string Dragon21Run = "Dragon_21@Run";
            
            public const string Dragon21Stand = "Dragon_21@Stand";
            
            public const string Dragon21Walk = "Dragon_21@Walk";
            
            public const string Dragon22 = "Dragon_22";
            
            public const string Dragon22Attack = "Dragon_22@Attack";
            
            public const string Dragon22AttackStand = "Dragon_22@AttackStand";
            
            public const string Dragon22Breath = "Dragon_22@Breath";
            
            public const string Dragon22Damage = "Dragon_22@Damage";
            
            public const string Dragon22Die = "Dragon_22@Die";
            
            public const string Dragon22Idle = "Dragon_22@Idle";
            
            public const string Dragon22Run = "Dragon_22@Run";
            
            public const string Dragon22Stand = "Dragon_22@Stand";
            
            public const string Dragon22Walk = "Dragon_22@Walk";
            
            public const string Dragon23 = "Dragon_23";
            
            public const string Dragon23Attack = "Dragon_23@Attack";
            
            public const string Dragon23AttackStand = "Dragon_23@AttackStand";
            
            public const string Dragon23Breath = "Dragon_23@Breath";
            
            public const string Dragon23Damage = "Dragon_23@Damage";
            
            public const string Dragon23Die = "Dragon_23@Die";
            
            public const string Dragon23Idle = "Dragon_23@Idle";
            
            public const string Dragon23Run = "Dragon_23@Run";
            
            public const string Dragon23Stand = "Dragon_23@Stand";
            
            public const string Dragon23Walk = "Dragon_23@Walk";
            
            public const string Dragon31 = "Dragon_31";
            
            public const string Dragon31Attack = "Dragon_31@Attack";
            
            public const string Dragon31AttackStand = "Dragon_31@AttackStand";
            
            public const string Dragon31Breath = "Dragon_31@Breath";
            
            public const string Dragon31Damage = "Dragon_31@Damage";
            
            public const string Dragon31Die = "Dragon_31@Die";
            
            public const string Dragon31Idle = "Dragon_31@Idle";
            
            public const string Dragon31Run = "Dragon_31@Run";
            
            public const string Dragon31Stand = "Dragon_31@Stand";
            
            public const string Dragon31Walk = "Dragon_31@Walk";
            
            public const string Dragon32 = "Dragon_32";
            
            public const string Dragon32Attack = "Dragon_32@Attack";
            
            public const string Dragon32AttackStand = "Dragon_32@AttackStand";
            
            public const string Dragon32Breath = "Dragon_32@Breath";
            
            public const string Dragon32Damage = "Dragon_32@Damage";
            
            public const string Dragon32Die = "Dragon_32@Die";
            
            public const string Dragon32Idle = "Dragon_32@Idle";
            
            public const string Dragon32Run = "Dragon_32@Run";
            
            public const string Dragon32Stand = "Dragon_32@Stand";
            
            public const string Dragon32Walk = "Dragon_32@Walk";
            
            public const string Dragon33 = "Dragon_33";
            
            public const string Dragon33Attack = "Dragon_33@Attack";
            
            public const string Dragon33AttackStand = "Dragon_33@AttackStand";
            
            public const string Dragon33Breath = "Dragon_33@Breath";
            
            public const string Dragon33Damage = "Dragon_33@Damage";
            
            public const string Dragon33Die = "Dragon_33@Die";
            
            public const string Dragon33Idle = "Dragon_33@Idle";
            
            public const string Dragon33Run = "Dragon_33@Run";
            
            public const string Dragon33Stand = "Dragon_33@Stand";
            
            public const string Dragon33Walk = "Dragon_33@Walk";
        }
        
        public sealed class PrefabsDragonEffects {
            
            public const string EffAttackStand = "Eff_AttackStand";
            
            public const string EffDamage = "Eff_Damage";
            
            public const string EffDeath = "Eff_Death";
            
            public const string EffEat = "Eff_Eat";
            
            public const string EffFireAttack1 = "Eff_FireAttack 1";
            
            public const string EffFireAttack2 = "Eff_FireAttack 2";
            
            public const string EffFireAttack3 = "Eff_FireAttack 3";
            
            public const string EffFireBreath1 = "Eff_FireBreath 1";
            
            public const string EffFireBreath2 = "Eff_FireBreath 2";
            
            public const string EffFireBreath3 = "Eff_FireBreath 3";
            
            public const string EffIceAttack1 = "Eff_IceAttack 1";
            
            public const string EffIceAttack2 = "Eff_IceAttack 2";
            
            public const string EffIceAttack3 = "Eff_IceAttack 3";
            
            public const string EffIceBreath1 = "Eff_IceBreath 1";
            
            public const string EffIceBreath2 = "Eff_IceBreath 2";
            
            public const string EffIceBreath3 = "Eff_IceBreath 3";
            
            public const string EffLightningAttack1 = "Eff_LightningAttack 1";
            
            public const string EffLightningAttack2 = "Eff_LightningAttack 2";
            
            public const string EffLightningAttack3 = "Eff_LightningAttack 3";
            
            public const string EffLightningBreath1 = "Eff_LightningBreath 1";
            
            public const string EffLightningBreath2 = "Eff_LightningBreath 2";
            
            public const string EffLightningBreath3 = "Eff_LightningBreath 3";
            
            public const string EffRun = "Eff_Run";
            
            public const string EffSleep = "Eff_Sleep";
            
            public const string EffStand1 = "Eff_Stand 1";
            
            public const string EffStand2 = "Eff_Stand 2";
            
            public const string EffStand3 = "Eff_Stand 3";
        }
        
        public sealed class TexturesAvartar {
            
            public const string _001Buttons = "00_1_Buttons";
            
            public const string _002Component = "00_2_Component";
            
            public const string _003FunctionIcons = "00_3_FunctionIcons";
            
            public const string _004EquipmentIcons = "00_4_EquipmentIcons";
            
            public const string _004Icons1 = "00_4_Icons1";
            
            public const string _004Icons2 = "00_4_Icons2";
            
            public const string _005GuildFlag = "00_5_Guild_Flag";
            
            public const string _006Chest = "00_6_Chest";
            
            public const string _01Login = "01_Login";
            
            public const string _02Title = "02_Title";
            
            public const string _03TitleStart = "03_TitleStart";
            
            public const string _04NetworkError = "04_NetworkError";
            
            public const string _05Home = "05_Home";
            
            public const string _06PopupLogin = "06_PopupLogin";
            
            public const string _07PopupSignup = "07_PopupSignup";
            
            public const string _08PopupOffline = "08_PopupOffline";
            
            public const string _09PopupName = "09_PopupName";
            
            public const string _10ADRemove = "10_ADRemove";
            
            public const string _11PopupChecking = "11_PopupChecking";
            
            public const string _12PopupEUALPrivacy = "12_PopupEUALPrivacy";
            
            public const string _13PopupUpdate = "13_PopupUpdate";
            
            public const string _14PopupMessage = "14_PopupMessage";
            
            public const string _20PlayType1 = "20_PlayType1";
            
            public const string _20PlayType2 = "20_PlayType2";
            
            public const string _20PlayType3 = "20_PlayType3";
            
            public const string _21PlayBoss = "21_PlayBoss";
            
            public const string _22PlayContinue = "22_PlayContinue";
            
            public const string _23PlayPause = "23_PlayPause";
            
            public const string _24PlayResult = "24_PlayResult";
            
            public const string _30Tutorial = "30_Tutorial";
            
            public const string _31CharacterSelect = "31_CharacterSelect";
            
            public const string _32Heroes = "32_Heroes";
            
            public const string _33Equipment = "33_Equipment";
            
            public const string _33EquipmentDetail1 = "33_EquipmentDetail1";
            
            public const string _33EquipmentDetail2 = "33_EquipmentDetail2";
            
            public const string _33EquipmentDetail3 = "33_EquipmentDetail3";
            
            public const string _34GuideBook = "34_GuideBook";
            
            public const string _40Stage = "40_Stage";
            
            public const string _41Setting = "41_Setting";
            
            public const string _42Language = "42_Language";
            
            public const string _43ShopChest = "43_Shop_Chest";
            
            public const string _44ShopGold = "44_Shop_Gold";
            
            public const string _45ShopGem = "45_Shop_Gem";
            
            public const string _46BattlePass = "46_BattlePass";
            
            public const string _47Missions = "47_Missions";
            
            public const string _48Guild = "48_Guild";
            
            public const string _50Ranking = "50_Ranking";
            
            public const string _60PowerSave = "60_PowerSave";
            
            public const string _61LoadingBar = "61_LoadingBar";
            
            public const string _62LevelUp = "62_LevelUp";
            
            public const string _63Rate = "63_Rate";
            
            public const string _64RewardDaily = "64_RewardDaily";
            
            public const string _65RewardWeek = "65_RewardWeek";
            
            public const string _66Roulette = "66_Roulette";
        }
    }
}
